#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/common.sh

last_build=$(cat $payload | jq -r .version.name)
info "Last known build: $last_build"

info "Triggering pipeline job: $pipeline/$job"
fly -t "$target" trigger-job -j $pipeline/$job
